apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-obfg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-obfg
    app.kubernetes.io/part-of: tkrw-pr714-0075-0063-app
  name: devfile-sample-obfg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-obfg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-obfg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0063-tenant/tkrw-pr714-0075-0063-app/devfile-sample-obfg@sha256:3b14dcea5ef90c4f6d9b15761695e21f5f753bc1e4e49db6093b226e3fcd8f3a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
