apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-obfg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0063-tenant/tkrw-pr714-0075-0063-app/devfile-sample-obfg@sha256:3b14dcea5ef90c4f6d9b15761695e21f5f753bc1e4e49db6093b226e3fcd8f3a
        name: my-nodejs
        resources: {}
status: {}
